using System;
using System.Collections.Generic;
using System.IO;
using ZPL2PDF.Shared;
using ZPL2PDF.Domain.Services;
using ZPL2PDF.Application.Interfaces;
using ZPL2PDF.Application.Services;
using ZPL2PDF.Infrastructure.Rendering;

namespace ZPL2PDF
{
    /// <summary>
    /// Handles conversion mode operations
    /// </summary>
    public class ConversionModeHandler
    {
        private readonly IConversionService _conversionService;
        private readonly IPathService _pathService;

        /// <summary>
        /// Initializes a new instance of the ConversionModeHandler
        /// </summary>
        public ConversionModeHandler()
        {
            _conversionService = new ConversionService();
            _pathService = new PathService();
        }

        /// <summary>
        /// Handles conversion mode operations
        /// </summary>
        /// <param name="argumentProcessor">The argument processor with conversion configuration</param>
        public void HandleConversion(ArgumentProcessor argumentProcessor)
        {
            // Read file content
            string fileContent;
            if (!string.IsNullOrEmpty(argumentProcessor.InputFilePath))
            {
                fileContent = LabelFileReader.ReadFile(argumentProcessor.InputFilePath);
            }
            else
            {
                fileContent = argumentProcessor.ZplContent;
            }

            // Determine output file name with priority:
            // 1. ^FX !FileName: from ZPL (FORCED - overrides everything) - HIGHEST priority
            // 2. -n parameter (explicit user choice)
            // 3. ^FX FileName: from ZPL content
            // 4. Input file name with .pdf extension (default - set by ArgumentParser)
            
            // First, check for FORCED file name (^FX !FileName:) - this overrides EVERYTHING
            var forcedFileName = _conversionService.ExtractForcedFileName(fileContent);
            if (!string.IsNullOrEmpty(forcedFileName))
            {
                if (!forcedFileName.EndsWith(".pdf", StringComparison.OrdinalIgnoreCase))
                {
                    forcedFileName += ".pdf";
                }
                argumentProcessor.OutputFileName = forcedFileName;
                Console.WriteLine($"Using FORCED file name from ZPL (!FileName): {forcedFileName}");
            }
            else
            {
                // Check if user explicitly provided -n parameter
                // ArgumentParser sets OutputFileName based on input file name if -n is not provided
                // We detect this by checking if the name matches the input file pattern
                string? inputFileBaseName = !string.IsNullOrEmpty(argumentProcessor.InputFilePath) 
                    ? Path.GetFileNameWithoutExtension(argumentProcessor.InputFilePath) + ".pdf"
                    : null;
                
                bool isAutoGeneratedName = argumentProcessor.OutputFileName == "output.pdf" 
                    || argumentProcessor.OutputFileName.StartsWith("ZPL2PDF_")
                    || argumentProcessor.OutputFileName == inputFileBaseName;
                
                if (isAutoGeneratedName)
                {
                    // Try to extract custom file name from ZPL content (^FX FileName: syntax)
                    var customFileName = _conversionService.ExtractFileName(fileContent);
                    if (!string.IsNullOrEmpty(customFileName))
                    {
                        // Use custom file name from ZPL, ensuring it has .pdf extension
                        if (!customFileName.EndsWith(".pdf", StringComparison.OrdinalIgnoreCase))
                        {
                            customFileName += ".pdf";
                        }
                        argumentProcessor.OutputFileName = customFileName;
                        Console.WriteLine($"Using custom file name from ZPL: {customFileName}");
                    }
                }
            }

            // Ensure the output folder exists
            _pathService.EnsureDirectoryExists(argumentProcessor.OutputFolderPath);

            string outputPdf = Path.Combine(argumentProcessor.OutputFolderPath, argumentProcessor.OutputFileName);

            // Use the new ConvertToPdf method with renderer support
            _conversionService.ConvertToPdf(
                fileContent,
                argumentProcessor.Width,
                argumentProcessor.Height,
                argumentProcessor.Unit,
                argumentProcessor.Dpi,
                argumentProcessor.RendererMode,
                outputPdf
            );

            Console.WriteLine($"PDF generated successfully: {outputPdf}");
        }
    }
}
