version: '3.8'

services:
  zpl2pdf:
    build: .
    container_name: zpl2pdf-daemon
    volumes:
      - ./watch:/app/watch
      - ./output:/app/output
      - ./config:/app/config
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - ZPL2PDF_LOG_LEVEL=Info
    command: start -l /app/watch -o /app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dotnet", "ZPL2PDF.dll", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service
  zpl2pdf-dev:
    build: .
    container_name: zpl2pdf-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./watch:/app/watch
      - ./output:/app/output
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - ZPL2PDF_LOG_LEVEL=Debug
    command: start -l /app/watch -o /app/output
    profiles:
      - dev

  # Test service
  zpl2pdf-test:
    build: .
    container_name: zpl2pdf-test
    volumes:
      - ./tests:/app/tests
      - ./test-data:/app/test-data
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - ZPL2PDF_LOG_LEVEL=Debug
    command: test
    profiles:
      - test

volumes:
  watch:
    driver: local
  output:
    driver: local
  config:
    driver: local
