# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: brunoleocam.ZPL2PDF
PackageVersion: 2.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  Custom: /ALLUSERS
UpgradeBehavior: install
Commands:
- ZPL2PDF
FileExtensions:
- txt
- prn
- zpl
ReleaseDate: 2025-01-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brunoleocam/ZPL2PDF/releases/download/v2.0.0/ZPL2PDF-Setup-2.0.0.exe
  InstallerSha256: REPLACE_WITH_ACTUAL_SHA256
  ProductCode: '{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
